### GET TOURS
GET http://localhost:8001/api/v1/tours

### GET TOUR BY ID
GET http://localhost:8001/api/v1/tours/5

### CREATE NEW TOUR
POST http://localhost:8001/api/v1/tours
Content-type: application/json

{
  "name": "Test Tour",
  "duration": "10",
  "difficulty": "easy",
  "price": "50"
}

### INCORRECTLY CREATE NEW TOUR
POST http://localhost:8001/api/v1/tours
Content-type: application/json

{
  "duration": "10",
  "difficulty": "easy",
  "price": "50"
}

### UPDATE TOUR BY ID
PATCH http://localhost:8001/api/v1/tours/17
Content-type: application/json

{
  "name": "Updated Tour",
  "duration": "10",
  "difficulty": "hard",
  "test": "test"
}

### DELETE TOUR BY ID
DELETE http://localhost:8001/api/v1/tours/17