### GET USERS
GET http://localhost:8001/api/v1/users

### GET USER BY ID
GET http://localhost:8001/api/v1/users/5

### CREATE NEW USER
POST http://localhost:8001/api/v1/users
Content-type: application/json

{
  "name": "Test user",
}

### UPDATE USER BY ID
PATCH http://localhost:8001/api/v1/users/17
Content-type: application/json

{
  "name": "Updated user",
}

### DELETE USER BY ID
DELETE http://localhost:8001/api/v1/users/14